"""initial schema: users, sources, raw_items, signals, opportunities, research, notifications, system_jobs

Revision ID: b715c3f3259b
Revises: 
Create Date: 2026-08-26 15:18:18.124598

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b715c3f3259b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opportunities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('slug', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('market', sa.String(length=64), nullable=True),
    sa.Column('target_user', sa.String(length=255), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('trend_score', sa.Float(), nullable=False),
    sa.Column('demand_score', sa.Float(), nullable=False),
    sa.Column('monetization_score', sa.Float(), nullable=False),
    sa.Column('competition_gap_score', sa.Float(), nullable=False),
    sa.Column('china_gap_score', sa.Float(), nullable=False),
    sa.Column('execution_score', sa.Float(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_opportunities_category'), 'opportunities', ['category'], unique=False)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.create_index(op.f('ix_opportunities_total_score'), 'opportunities', ['total_score'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('crawl_interval', sa.Integer(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retry', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('raw_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_source_external')
    )
    op.create_index(op.f('ix_raw_items_content_hash'), 'raw_items', ['content_hash'], unique=False)
    op.create_index(op.f('ix_raw_items_source_id'), 'raw_items', ['source_id'], unique=False)
    op.create_table('research_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_jobs_opportunity_id'), 'research_jobs', ['opportunity_id'], unique=False)
    op.create_table('research_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('market_analysis', sa.Text(), nullable=True),
    sa.Column('competition_analysis', sa.Text(), nullable=True),
    sa.Column('china_analysis', sa.Text(), nullable=True),
    sa.Column('monetization_analysis', sa.Text(), nullable=True),
    sa.Column('mvp_analysis', sa.Text(), nullable=True),
    sa.Column('risk_analysis', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.String(length=64), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('sources_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_reports_opportunity_id'), 'research_reports', ['opportunity_id'], unique=False)
    op.create_table('opportunity_sources',
    sa.Column('opportunity_id', sa.Integer(), nullable=False),
    sa.Column('raw_item_id', sa.Integer(), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_item_id'], ['raw_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('opportunity_id', 'raw_item_id'),
    sa.UniqueConstraint('opportunity_id', 'raw_item_id', name='uq_opp_raw')
    )
    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('raw_item_id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=64), nullable=False),
    sa.Column('keyword', sa.String(length=128), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('velocity_score', sa.Float(), nullable=False),
    sa.Column('engagement_score', sa.Float(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['raw_item_id'], ['raw_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_raw_item_id'), 'signals', ['raw_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_raw_item_id'), table_name='signals')
    op.drop_table('signals')
    op.drop_table('opportunity_sources')
    op.drop_index(op.f('ix_research_reports_opportunity_id'), table_name='research_reports')
    op.drop_table('research_reports')
    op.drop_index(op.f('ix_research_jobs_opportunity_id'), table_name='research_jobs')
    op.drop_table('research_jobs')
    op.drop_index(op.f('ix_raw_items_source_id'), table_name='raw_items')
    op.drop_index(op.f('ix_raw_items_content_hash'), table_name='raw_items')
    op.drop_table('raw_items')
    op.drop_table('users')
    op.drop_table('system_jobs')
    op.drop_table('sources')
    op.drop_index(op.f('ix_opportunities_total_score'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_category'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_table('notifications')
    # ### end Alembic commands ###