"""MarkdownV2 formatters for the daily digest + per-opportunity alerts.

Telegram's MarkdownV2 has a long list of reserved characters that MUST
be escaped when they appear in user-supplied text:

    _  *  [  ]  (  )  ~  `  >  #  +  -  =  |  {  }  .  !

If even one is left unescaped the whole message is rejected. We escape
defensively at every boundary (titles, summaries, source titles).

The 4096-char Telegram limit is enforced by `truncate_to_telegram_limit`.
"""

from __future__ import annotations

import re
from collections.abc import Iterable
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any, Optional


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
TELEGRAM_MAX_TEXT = 4096
TELEGRAM_RECOMMEND_EMOJI = {
    "strongly_recommend": "🟢",
    "recommend": "🟢",
    "watch": "🟡",
    "not_recommended": "🔴",
    "insufficient_data": "⚪",
}
# MarkdownV2 reserved characters — order matters for the escape regex below.
# Inside the character class we MUST escape `]` (terminator) and `-` (range).
_MARKDOWNV2_RESERVED = r"_*[\]()~`>#+\-=|{}.!"


# ---------------------------------------------------------------------------
# Escaping
# ---------------------------------------------------------------------------
def escape_markdown_v2(text: str) -> str:
    """Escape every MarkdownV2 reserved character.

    Also collapses internal newlines (Telegram treats a bare `\\n` as a
    line break but our messages are designed for single-line snippets).
    """
    if text is None:
        return ""
    # Escape backslash first, then reserved chars.
    escaped = str(text).replace("\\", "\\\\")
    escaped = re.sub(r"([" + _MARKDOWNV2_RESERVED + r"])", r"\\\1", escaped)
    return escaped


def truncate_to_telegram_limit(text: str, *, limit: int = TELEGRAM_MAX_TEXT) -> str:
    """Truncate to `limit` chars, leaving room for the trailing ellipsis."""
    if text is None:
        return ""
    if len(text) <= limit:
        return text
    if limit <= 1:
        return text[:limit]
    return text[: limit - 1] + "…"


def truncate_text(text: str, *, limit: int) -> str:
    """Plain-text truncation (used for snippets that are NOT markdown)."""
    if text is None:
        return ""
    if len(text) <= limit:
        return text
    return text[: max(0, limit - 1)] + "…"


# ---------------------------------------------------------------------------
# Data carrier — used by the service to feed both the formatter and the
# Notification row payload without coupling to SQLAlchemy models.
# ---------------------------------------------------------------------------
@dataclass(slots=True)
class DigestEntry:
    """One item inside the daily digest."""

    opportunity_id: int
    title: str
    slug: str
    total_score: float
    recommendation: str
    summary: str
    category: Optional[str] = None
    target_user: Optional[str] = None
    trend_score: float = 0.0
    demand_score: float = 0.0
    monetization_score: float = 0.0
    competition_gap_score: float = 0.0
    china_gap_score: float = 0.0
    execution_score: float = 0.0
    source_count: int = 0
    has_report: bool = False

    def score_label(self) -> str:
        return f"{self.total_score:.1f}"

    def sub_scores_block(self) -> str:
        return (
            f"Trend {self.trend_score:.0f} \\| Demand {self.demand_score:.0f} \\| "
            f"Mon {self.monetization_score:.0f} \\| Gap {self.competition_gap_score:.0f} \\| "
            f"CN {self.china_gap_score:.0f} \\| Exec {self.execution_score:.0f}"
        )


# ---------------------------------------------------------------------------
# Builders
# ---------------------------------------------------------------------------
def format_digest(
    *,
    entries: Iterable[DigestEntry],
    base_url: str,
    generated_at: Optional[datetime] = None,
    header: str = "*AI Opportunity Radar — Daily Digest*",
    max_entries: int = 5,
    per_entry_summary_chars: int = 240,
    footer: str = "_Generated by the radar\\. Tap an opportunity for the full report\\._",
) -> str:
    """Build the daily-digest MarkdownV2 message.

    The message is single Telegram-message sized (under `TELEGRAM_MAX_TEXT`).
    """
    items = list(entries)[:max_entries]
    if generated_at is None:
        generated_at = datetime.now(timezone.utc)

    lines: list[str] = [escape_markdown_v2(header), ""]
    if not items:
        lines.append(
            escape_markdown_v2(
                "No opportunities crossed the research threshold today\\."
            )
        )
    else:
        for idx, entry in enumerate(items, start=1):
            emoji = TELEGRAM_RECOMMEND_EMOJI.get(entry.recommendation, "•")
            title_escaped = escape_markdown_v2(entry.title)
            score_label = escape_markdown_v2(entry.score_label())
            rec_label = escape_markdown_v2(entry.recommendation.replace("_", " "))
            url = f"{base_url.rstrip('/')}/opportunities/{entry.slug}"
            url_escaped = escape_markdown_v2(url)
            summary = truncate_text(entry.summary or "", limit=per_entry_summary_chars)
            summary_escaped = escape_markdown_v2(summary)
            cat = (
                escape_markdown_v2(entry.category)
                if entry.category
                else "uncategorised"
            )

            lines.append(
                f"{idx}\\. {emoji} *{title_escaped}* \\(score {score_label}\\)"
            )
            lines.append(f"   Category: {cat} \\| {rec_label}")
            if summary_escaped:
                lines.append(f"   {summary_escaped}")
            lines.append(f"   [Open]({url_escaped})")
            lines.append("")

    lines.append(escape_markdown_v2(footer))
    text = "\n".join(lines).rstrip() + "\n"
    return truncate_to_telegram_limit(text)


def format_opportunity_alert(
    *,
    entry: DigestEntry,
    base_url: str,
    extra_note: Optional[str] = None,
    max_summary_chars: int = 600,
) -> str:
    """Build a single-opportunity alert message (MarkdownV2)."""
    emoji = TELEGRAM_RECOMMEND_EMOJI.get(entry.recommendation, "•")
    title_escaped = escape_markdown_v2(entry.title)
    score_label = escape_markdown_v2(entry.score_label())
    rec_label = escape_markdown_v2(entry.recommendation.replace("_", " "))
    url = f"{base_url.rstrip('/')}/opportunities/{entry.slug}"
    url_escaped = escape_markdown_v2(url)
    summary = truncate_text(entry.summary or "", limit=max_summary_chars)
    summary_escaped = escape_markdown_v2(summary)
    cat = (
        escape_markdown_v2(entry.category) if entry.category else "uncategorised"
    )
    target = (
        escape_markdown_v2(entry.target_user) if entry.target_user else "—"
    )

    lines: list[str] = [
        f"{emoji} *{title_escaped}*",
        f"Score *{score_label}* \\| {rec_label} \\| {cat}",
        f"Target user: {target}",
        f"Sub\\-scores: {escape_markdown_v2(entry.sub_scores_block())}",
    ]
    if summary_escaped:
        lines.append("")
        lines.append(summary_escaped)
    if extra_note:
        lines.append("")
        lines.append(escape_markdown_v2(extra_note))
    lines.append("")
    lines.append(f"[Open report]({url_escaped})")
    text = "\n".join(lines).rstrip() + "\n"
    return truncate_to_telegram_limit(text)


# ---------------------------------------------------------------------------
# Validation helper — used by tests + the service to detect malformed
# messages before they hit Telegram.
# ---------------------------------------------------------------------------
_UNESCAPED_TOKEN_RE = re.compile(r"(?<!\\)([" + _MARKDOWNV2_RESERVED + r"])")


def assert_markdown_v2_safe(text: str) -> list[str]:
    """Return a list of human-readable warnings about unsafe characters.

    Empty list means the message should pass Telegram's parser. Note that
    `assert_markdown_v2_safe` checks for unbalanced `[...]` parens too.
    """
    warnings: list[str] = []
    if text is None:
        return warnings
    if len(text) > TELEGRAM_MAX_TEXT:
        warnings.append(
            f"text exceeds {TELEGRAM_MAX_TEXT} chars ({len(text)})"
        )
    # Quick check for obviously unescaped reserved chars — escape_markdown_v2
    # always doubles them, so an unescaped occurrence in user-supplied text
    # is a bug. NOTE: this is intended for raw text validation, NOT for the
    # formatter output (which contains intentional markdown like `*bold*`,
    # `[link](...)`, etc.). Use `assert_markdown_v2_safe(raw_text)` on
    # untrusted strings before they hit the formatter.
    for match in _UNESCAPED_TOKEN_RE.finditer(text):
        warnings.append(f"unescaped character: {match.group(1)!r}")
        if len(warnings) >= 5:
            break
    return warnings


__all__ = [
    "DigestEntry",
    "TELEGRAM_MAX_TEXT",
    "TELEGRAM_RECOMMEND_EMOJI",
    "assert_markdown_v2_safe",
    "escape_markdown_v2",
    "format_digest",
    "format_opportunity_alert",
    "truncate_text",
    "truncate_to_telegram_limit",
]
